version: '3'

services:
  web:
    image: nginx
    volumes:
      - ./public:/var/www/html/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    ports:
      - "3000:80"
    container_name: project_nginx
